# Generated by Django 4.2.18 on 2025-02-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fixed_deduction',
            field=models.PositiveIntegerField(default=1, verbose_name='每次课扣除课时'),
        ),
    ]
