# Generated by Django 4.2.18 on 2025-02-17 03:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_course_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='总课时数'),
        ),
    ]
