# Generated by Django 4.2.18 on 2025-02-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='ClassroomPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateField(auto_now_add=True)),
                ('rating', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='students.enrollment')),
            ],
        ),
    ]
