# Generated by Django 4.2.18 on 2025-02-18 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_avatar_url_classroomperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.enrollment', verbose_name='报课记录'),
        ),
    ]
