# Generated by Django 4.2.18 on 2025-02-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_attendance_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomperformance',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomperformance',
            name='expression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomperformance',
            name='focus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomperformance',
            name='logical_thinking',
            field=models.IntegerField(default=0),
        ),
    ]
